version: '3'

services:
    db:
        image: postgres:11.1-alpine
        command: postgres -c log_min_error_statement=WARNING
        user: postgres
        volumes:
            - web-db:/var/lib/postgresql/data:Z
        environment:
            POSTGRES_USER: ${DB_USER}
            POSTGRES_PASSWORD: ${DB_PASSWORD}
        restart: unless-stopped
    rabbitmq:
        image: 'rabbitmq:3.7-alpine'
        environment:
            RABBITMQ_DEFAULT_USER: ${RMQ_USER}
            RABBITMQ_DEFAULT_PASS: ${RMQ_PASSWORD}
        restart: unless-stopped
    uwsgi:
        image: dhv_app
        build: 
            context: .
            dockerfile: dockerfiles/uwsgi.dockerfile
        command: sh -c "python manage.py collectstatic --noinput && python manage.py migrate && uwsgi --ini /code/django-hls-video"
        environment:
            RMQ_USER: ${RMQ_USER}
            RMQ_PASSWORD: ${RMQ_PASSWORD}
            POSTGRES_USER: ${DB_USER}
            POSTGRES_PASSWORD: ${DB_PASSWORD}
            PROD: ${UWSGI_PROD}
            SECRET_KEY: ${SECRET_KEY}
        volumes:
            - static-content:/code/static:z
            - media-files:/code/media:z
        depends_on:
            - db
            - rabbitmq
        restart: unless-stopped
    default_workers:
        image: dhv_app
        command: celery -A django_hls_video worker -c 5 -l WARNING -E
        environment:
            RMQ_USER: ${RMQ_USER}
            RMQ_PASSWORD: ${RMQ_PASSWORD}
            POSTGRES_USER: ${DB_USER}
            POSTGRES_PASSWORD: ${DB_PASSWORD}
            SECRET_KEY: ${SECRET_KEY}
            PROD: ${UWSGI_PROD}
        volumes:
            - media-files:/code/media
        depends_on:
            - db
            - rabbitmq
            - uwsgi
        restart: unless-stopped
    encoding_worker:
        image: dhv_app
        command: celery -A django_hls_video worker -Q encoding_queue -c 1 -l WARNING -E
        environment:
            RMQ_USER: ${RMQ_USER}
            RMQ_PASSWORD: ${RMQ_PASSWORD}
            POSTGRES_USER: ${DB_USER}
            POSTGRES_PASSWORD: ${DB_PASSWORD}
            SECRET_KEY: ${SECRET_KEY}
            PROD: ${UWSGI_PROD}
        volumes:
            - media-files:/code/media
        depends_on:
            - db
            - rabbitmq
            - uwsgi
        restart: unless-stopped
    daphne:
        image: dhv_app
        environment:
            RMQ_USER: ${RMQ_USER}
            RMQ_PASSWORD: ${RMQ_PASSWORD}
            POSTGRES_USER: ${DB_USER}
            POSTGRES_PASSWORD: ${DB_PASSWORD}
            SECRET_KEY: ${SECRET_KEY}
        command: daphne -b 0.0.0.0 -p 8002 django_hls_video.asgi:application
        volumes:
            - media-files:/code/media:ro
        depends_on:
            - db
            - rabbitmq
        restart: unless-stopped
    nginx:
        image: nginx:1.15.8-alpine
        ports: 
            - "4002:80"
        volumes:
            - static-content:/static:ro
            - media-files:/media:ro
            - ./config/nginx/conf.d:/etc/nginx/conf.d:Z
        depends_on:
            - daphne
            - uwsgi
        restart: unless-stopped

volumes:
    static-content:
    web-db:
    media-files:

