version: '3'

volumes:
    static-content:
    web-db:
        driver: local

services:
    db:
        image: postgres:11.1-alpine
        command: postgres -c log_min_error_statement=WARNING
        user: postgres
        volumes:
            - web-db:/var/lib/postgresql/data
        environment:
            POSTGRES_USER: ${DB_USER}
            POSTGRES_PASSWORD: ${DB_PASSWORD}
        restart: always
    redis:
        image: redis:5.0.3-alpine
        command: redis-server --loglevel warning
        sysctls:
            net.core.somaxconn: '511'
        restart: always
    uwsgi:
        image: dhv_app
        build: 
            context: .
            dockerfile: dockerfiles/uwsgi.dockerfile
        command: bash -c "python manage.py collectstatic --noinput && python manage.py migrate && uwsgi --ini /code/django-hls-video"
        environment:
            POSTGRES_USER: ${DB_USER}
            POSTGRES_PASSWORD: ${DB_PASSWORD}
            PROD: ${UWSGI_PROD}
            SECRET_KEY: ${SECRET_KEY}
        volumes:
            - static-content:/code/static
            - ${MEDIA_PATH}:/code/media
        depends_on:
            - db
            - redis
        restart: always
    celery:
        image: dhv_app
        command: celery -A django_hls_video worker -l WARNING
        environment:
            POSTGRES_USER: ${DB_USER}
            POSTGRES_PASSWORD: ${DB_PASSWORD}
            SECRET_KEY: ${SECRET_KEY}
        volumes:
            - ${MEDIA_PATH}:/code/media
        depends_on:
            - db
            - redis
        restart: always
    flower:
        image: mher/flower
        command: flower --broker=redis://redis:6379/0 --port=8888 --url-prefix=flower
        depends_on:
            - redis
            - celery
        restart: always
    daphne:
        image: dhv_app
        environment:
            POSTGRES_USER: ${DB_USER}
            POSTGRES_PASSWORD: ${DB_PASSWORD}
            SECRET_KEY: ${SECRET_KEY}
        command: daphne -b 0.0.0.0 -p 8002 django_hls_video.asgi:application
        volumes:
            - ${MEDIA_PATH}:/code/media
        depends_on:
            - db
            - redis
        restart: always
    nginx:
        image: nginx:1.15.8-alpine
        ports: 
            - "8001:80"
        volumes:
            - static-content:/static
            - ./config/nginx/conf.d:/etc/nginx/conf.d
            - ${MEDIA_PATH}:/media
        depends_on:
            - daphne
            - uwsgi
        restart: always

