version: '3'

services:
    db:
        image: postgres:11.1-alpine
        command: postgres -c log_min_error_statement=WARNING
        user: postgres
        volumes:
            - web-db:/var/lib/postgresql/data:Z
        environment:
            POSTGRES_USER: ${DB_USER}
            POSTGRES_PASSWORD: ${DB_PASSWORD}
        restart: always
    redis:
        image: redis:5.0.3-alpine
        command: redis-server --loglevel warning
        sysctls:
            net.core.somaxconn: '511'
        restart: always
    uwsgi:
        image: dhv_app
        build: 
            context: .
            dockerfile: dockerfiles/uwsgi.dockerfile
        command: bash -c "python manage.py collectstatic --noinput && python manage.py migrate && uwsgi --ini /code/django-hls-video"
        environment:
            POSTGRES_USER: ${DB_USER}
            POSTGRES_PASSWORD: ${DB_PASSWORD}
            PROD: ${UWSGI_PROD}
            SECRET_KEY: ${SECRET_KEY}
        volumes:
            - static-content:/code/static:z
            - media-files:/code/media:z
        depends_on:
            - db
            - redis
        restart: always
    default_workers:
        image: dhv_app
        command: celery -A django_hls_video worker -c 5 -l WARNING -E
        environment:
            POSTGRES_USER: ${DB_USER}
            POSTGRES_PASSWORD: ${DB_PASSWORD}
            SECRET_KEY: ${SECRET_KEY}
            PROD: ${UWSGI_PROD}
        volumes:
            - media-files:/code/media
        depends_on:
            - db
            - redis
            - uwsgi
        restart: always
    encoding_worker:
        image: dhv_app
        command: celery -A django_hls_video worker -Q encoding_queue -c 1 -l WARNING -E
        environment:
            POSTGRES_USER: ${DB_USER}
            POSTGRES_PASSWORD: ${DB_PASSWORD}
            SECRET_KEY: ${SECRET_KEY}
            PROD: ${UWSGI_PROD}
        volumes:
            - media-files:/code/media
        depends_on:
            - db
            - redis
            - uwsgi
        restart: always
    daphne:
        image: dhv_app
        environment:
            POSTGRES_USER: ${DB_USER}
            POSTGRES_PASSWORD: ${DB_PASSWORD}
            SECRET_KEY: ${SECRET_KEY}
        command: daphne -b 0.0.0.0 -p 8002 django_hls_video.asgi:application
        volumes:
            - media-files:/code/media:ro
        depends_on:
            - db
            - redis
        restart: always
    nginx:
        image: nginx:1.15.8-alpine
        ports: 
            - "4002:80"
        volumes:
            - static-content:/static:ro
            - media-files:/media:ro
            - ./config/nginx/conf.d:/etc/nginx/conf.d:Z
        depends_on:
            - daphne
            - uwsgi
        restart: always

volumes:
    static-content:
    web-db:
    media-files:

